version: 2.1

orbs:
  node-packages: circleci-orbs/node-orb@0.0.1
  docker-build: circleci-orbs/docker-orb@0.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node-packages/install-packages
      - docker-build/build-and-push:
          requires:
            - node-packages/install-packages